service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: false

name:
  container: mysql
  initContainer:
  service: mysql-service
  cluster: mysql-cluster

  # 与 volumeMounts 中的 name 一致
  volume:
  configMap:

  # 与 volumeMounts 中的 name 一致
  pvc: mysql-storage
  storageClass: retain-storage-class

image:
  container: crpi-iay62pbhw1a58p10.cn-hangzhou.personal.cr.aliyuncs.com/visage-arm64/mysql:8.0
  initContainer:
  imagePullPolicy: IfNotPresent
  replicas: 1
  imagePullSecret: my-registry-secret

ConfigMap:
  fileName:
  filePath:

pvc:
  storage: 1Gi
  accessModes: ReadWriteOnce
  path: /var/lib/mysql

storageClass:
  provisioner: k8s.io/minikube-hostpath
  reclaimPolicy: Retain
  volumeBindingMode: Immediate


# 自定义配置
env:
  password: zxj201328  # MySQL root 用户的密码
