apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql  # StatefulSet 的名称，通常是 MySQL 服务的名称
spec:
  serviceName: mysql-service  # 关联的 headless service 名称，用于网络发现
  replicas: 1  # 设置 Pod 副本数，这里是 1
  selector:
    matchLabels:
      app: mysql  # 用于选择具有 app: mysql 标签的 Pod
  template:
    metadata:
      labels:
        app: mysql  # 为 Pod 添加标签 app: mysql
    spec:
      containers:
        - name: mysql  # 容器的名称
          image: crpi-iay62pbhw1a58p10.cn-hangzhou.personal.cr.aliyuncs.com/visage-namespace/mysql:5.7  # MySQL 镜像
          imagePullPolicy: IfNotPresent  # 如果本地已有镜像则不再拉取
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "zxj201328"  # MySQL root 用户的密码（生产环境应使用 Secret 管理）
          ports:
            - containerPort: 3306  # 容器内部 MySQL 服务的端口
          volumeMounts:
            - mountPath: "/var/lib/mysql"  # 容器内数据存储路径，MySQL 数据库默认存储位置
              name: mysql-storage  # 关联 volume 的名称（必须与 volumeClaimTemplates 中的名称一致）
      imagePullSecrets:
        - name: my-registry-secret  # 如果需要从私有镜像仓库拉取镜像，指定镜像仓库的 Secret
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage  # PVC 的名称，StatefulSet 会为每个 Pod 自动创建与此名称相关的 PVC
      spec:
        accessModes:
          - ReadWriteOnce  # 数据只能由一个 Pod 读写
        resources:
          requests:
            storage: 1Gi  # 为每个 Pod 分配 1Gi 存储
        storageClassName: retain-storage-class  # 使用自定义的，回收策略为保留的storageClass