apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retain-storage-class  # 自定义 StorageClass 的名称
provisioner: k8s.io/minikube-hostpath  # Minikube 本地存储供应器
reclaimPolicy: Retain  # 设置回收策略为 Retain
volumeBindingMode: Immediate  # 立即绑定存储卷