service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

name:
  container: backend
  initContainer:
  service: backend-service
  cluster: backend-cluster

  # 与 volumeMounts 中的 name 一致
  volume:
  configMap:

  # 与 volumeMounts 中的 name 一致
  pvc:
  storageClass:

image:
  container: crpi-iay62pbhw1a58p10.cn-hangzhou.personal.cr.aliyuncs.com/visage-namespace/backend-boot-template:0.0.3
  initContainer:
  imagePullPolicy: IfNotPresent
  replicas: 2
  imagePullSecret: my-registry-secret

ConfigMap:
  fileName:
  filePath:

pvc:
  storage:
  accessModes:
  path:

storageClass:
  provisioner:
  reclaimPolicy:
  volumeBindingMode:


# 自定义配置

