apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.service }}
spec:
  selector:
    app: {{ .Values.name.container }}
  ports:
    - name: redis
      protocol: TCP
      # Service 在 Kubernetes 集群内部暴露的端口
      port: {{ .Values.service.port }}
      # pod 内部 Redis 进程监听的端口
      targetPort: {{ .Values.service.port }}

    - name: clusterbus
      protocol: TCP
      # Redis Cluster 节点之间通信的端口，通常是主端口 + 10000
      port: {{ add .Values.service.port 10000 }}
      targetPort: {{ add .Values.service.port 10000 }}

  # 无头服务，适合用于 StatefulSet，让客户端能直接获取每个 Pod 的 IP
  clusterIP: None