# 使用  ServiceAccount + Role + RoleBinding 来赋予容器内访问 Kubernetes API 的权限。
# 在 Job 中指定 serviceAccountName: redis-cluster-job-sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cluster-job-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-cluster-job-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-cluster-job-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: redis-cluster-job-sa
    namespace: default
roleRef:
  kind: Role
  name: redis-cluster-job-role
  apiGroup: rbac.authorization.k8s.io