apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.service }}
spec:
  selector:
    app: {{ .Values.name.container}} # 服务会选择匹配此标签的 Pod
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}         # Service 在 Kubernetes 集群内部暴露的端口
      targetPort: {{ .Values.service.port}}   #  Pod 内部进程监听的端口
  type: ClusterIP  # 仅限于集群内访问,通过 backend-service 这个 DNS 名称解析后的IP进行负载均衡访问