apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name.configMap }}
data:
  # requirepass Redis 密码
  # cluster-enabled 是否启用集群模式
  # loglevel 设置 Redis 日志的级别
  # maxmemory 设置 Redis 的最大内存使用量
  # maxclients 设置 Redis 允许的最大客户端连接数
  # save 设置 RDB 快照的保存间隔
  # appendonly 是否启用 AOF 持久化
  # appendfsync 设置 AOF 文件的同步策略
  # port Redis 服务的端口
  # dir Redis 数据存储路径
  redis.conf: |
    requirepass {{ .Values.env.password }}
    cluster-enabled {{ .Values.env.cluster_enabled }}
    loglevel {{ .Values.env.log_level }}
    maxmemory {{ .Values.env.max_memory }}
    maxclients {{ .Values.env.max_clients }}
    save {{ .Values.env.rdb_save_interval }}
    appendonly {{ .Values.env.aof_enabled }}
    appendfsync {{ .Values.env.aof_fsync }}
    port {{ .Values.service.port }}
    dir {{ .Values.pvc.path }}